# _config.yml
title: "The Pinc Kactus Museum"
baseurl: ""        # root of your domain
url: "https://pinckactus.github.io"
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  bot_docs:
    output: true
    permalink: /bot/:path/
