# netlify.toml

[build]
  command = "npm run build"
  publish = "_site"

[dev]
  # first build (including encryption), then serve for local testing
  command   = "npm run build && bundle exec jekyll serve --livereload --port 4001"
  port      = 8888
  functions = "netlify/functions"
